"""Task-independent OWL semantics + task-conditioned set actor.

The tracker supplies [px, py, vx, vy, owl_appearance_512].  A shared learned
projector maps appearance to 16 dimensions, giving the formal n x 20 entity
matrix consumed by the actor.  Qwen task embeddings enter only through the
hypernetwork.
"""

from __future__ import annotations

import math
import numpy as np
import torch
import torch.nn as nn

E_MAX = 16
KIN_DIM = 4
OWL_DIM = 512
SEMANTIC_DIM = 16
RAW_DIM = KIN_DIM + OWL_DIM
ENTITY_DIM = KIN_DIM + SEMANTIC_DIM
TASK_DIM = 64


def appearance_match_index(raw_entities, reference, minimum_similarity: float = 0.80):
    """Return the row matching a locked OWL appearance, or ``(None, score)``."""
    raw = np.asarray(raw_entities, dtype=np.float64)
    ref = np.asarray(reference, dtype=np.float64).reshape(-1)
    if raw.ndim != 2 or raw.shape[0] == 0 or raw.shape[1] < KIN_DIM + ref.size:
        return None, -1.0
    candidates = raw[:, KIN_DIM : KIN_DIM + ref.size]
    ref_norm = float(np.linalg.norm(ref))
    norms = np.linalg.norm(candidates, axis=1)
    denom = norms * ref_norm
    similarities = np.divide(
        candidates @ ref,
        denom,
        out=np.full(len(candidates), -1.0, dtype=np.float64),
        where=denom > 1e-9,
    )
    index = int(np.argmax(similarities))
    score = float(similarities[index])
    return (index if score >= float(minimum_similarity) else None), score


def pack_raw_entities(raw_entities) -> tuple[np.ndarray, np.ndarray]:
    raw = np.asarray(raw_entities, dtype=np.float64)
    if raw.size == 0:
        raw = np.zeros((0, RAW_DIM), dtype=np.float64)
    if raw.ndim != 2 or raw.shape[1] != RAW_DIM:
        raise ValueError(f"raw entities expected (n,{RAW_DIM}), got {raw.shape}")
    n = min(int(raw.shape[0]), E_MAX)
    padded = np.zeros((E_MAX, RAW_DIM), dtype=np.float64)
    mask = np.zeros(E_MAX, dtype=np.bool_)
    if n:
        padded[:n] = raw[:n]
        mask[:n] = True
    return padded, mask


class SemanticProjector(nn.Module):
    """Shared trainable OWL-512 -> semantic-16 projection."""

    def __init__(self, hidden: int = 64) -> None:
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(OWL_DIM, int(hidden)),
            nn.ReLU(),
            nn.Linear(int(hidden), SEMANTIC_DIM),
        )

    def forward(self, appearance: torch.Tensor) -> torch.Tensor:
        feature = self.net(appearance)
        return torch.nn.functional.normalize(feature, dim=-1, eps=1e-8)


class SemanticCanonization(nn.Module):
    """Canonicalize only position/velocity; semantic columns stay untouched."""

    def __init__(self, eps: float = 1e-6) -> None:
        super().__init__()
        self.eps = float(eps)

    def forward(self, state: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
        m = mask.unsqueeze(-1).to(state.dtype)
        p = state[..., :2] * m
        gram = p.transpose(-2, -1) @ p
        values, vectors = torch.linalg.eigh(gram)
        axis = vectors[..., -1]
        anchor = p.sum(dim=-2)
        alignment = (axis * anchor).sum(dim=-1)
        axis = torch.where((alignment < 0).unsqueeze(-1), -axis, axis)
        theta = torch.atan2(axis[..., 1], axis[..., 0])
        gap = values[..., -1] - values[..., -2]
        theta = torch.where(gap < self.eps, torch.zeros_like(theta), theta)
        c = torch.cos(theta).unsqueeze(-1)
        s = torch.sin(theta).unsqueeze(-1)
        out = state.clone()
        px, py = state[..., 0], state[..., 1]
        vx, vy = state[..., 2], state[..., 3]
        out[..., 0] = px * c + py * s
        out[..., 1] = -px * s + py * c
        out[..., 2] = vx * c + vy * s
        out[..., 3] = -vx * s + vy * c
        return out * m


class TaskHyperNetwork(nn.Module):
    def __init__(self, task_dim: int = TASK_DIM, value_dim: int = 16, hidden: int = 32) -> None:
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(int(task_dim), int(hidden)),
            nn.ReLU(),
            nn.Linear(int(hidden), int(hidden)),
            nn.ReLU(),
            nn.Linear(int(hidden), 2 * int(value_dim)),
        )
        self.value_dim = int(value_dim)

    def forward(self, task: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        value = self.net(task)
        return value[..., : self.value_dim], value[..., self.value_dim :]


class PolarControlHead(nn.Module):
    """SO(2)-equivariant control from selected target kinematics.

    Entity semantics choose the target.  Once selected, range and relative
    velocity determine radial/tangential motion, with Qwen conditioning
    supplied only through FiLM parameters generated by the task hypernetwork.
    """

    def __init__(self, task_dim: int = TASK_DIM, hidden: int = 32) -> None:
        super().__init__()
        self.state = nn.Sequential(nn.Linear(4, hidden), nn.ReLU(), nn.Linear(hidden, hidden))
        self.task_film = nn.Sequential(
            nn.Linear(int(task_dim), hidden),
            nn.ReLU(),
            nn.Linear(hidden, 2 * hidden),
        )
        self.out = nn.Linear(hidden, 2)

    def forward(self, kinematics: torch.Tensor, conditioned_task: torch.Tensor) -> torch.Tensor:
        p = kinematics[..., :2]
        v = kinematics[..., 2:4]
        distance = torch.linalg.norm(p, dim=-1, keepdim=True).clamp_min(1.0e-6)
        radial = p / distance
        tangent = torch.stack((-radial[..., 1], radial[..., 0]), dim=-1)
        radial_v = (v * radial).sum(dim=-1, keepdim=True)
        tangent_v = (v * tangent).sum(dim=-1, keepdim=True)
        r10 = distance / 10.0
        invariant = torch.cat((r10, r10 * r10, radial_v / 2.0, tangent_v / 2.0), dim=-1)
        state = self.state(invariant)
        gamma, beta = self.task_film(conditioned_task).chunk(2, dim=-1)
        coefficients = torch.tanh(self.out(torch.relu(state * (1.0 + gamma) + beta)))
        return coefficients[..., :1] * radial + coefficients[..., 1:] * tangent


class SemanticAttentionActor(nn.Module):
    """Joint semantic projector and SO(2)-equivariant task-conditioned actor."""

    def __init__(
        self,
        task_dim: int = TASK_DIM,
        width: int = 16,
        max_action: float = 0.5,
        use_task_selector: bool = True,
        use_null_selector: bool = True,
        use_polar_control: bool = False,
        task_center=None,
        task_scale: float = 1.0,
    ) -> None:
        super().__init__()
        self.projector = SemanticProjector()
        self.canonize = SemanticCanonization()
        self.w_q = nn.Linear(ENTITY_DIM, int(width), bias=False)
        self.w_k = nn.Linear(ENTITY_DIM, int(width), bias=False)
        self.w_v = nn.Linear(ENTITY_DIM, int(width), bias=False)
        self.w_o = nn.Linear(int(width), 1, bias=False)
        self.hypernet = TaskHyperNetwork(task_dim=task_dim, value_dim=width)
        self.use_task_selector = bool(use_task_selector)
        self.use_null_selector = bool(use_null_selector and use_task_selector)
        self.use_polar_control = bool(use_polar_control and use_task_selector)
        if self.use_task_selector:
            self.w_select = nn.Linear(ENTITY_DIM, int(width), bias=False)
            self.selector_hypernet = nn.Sequential(
                nn.Linear(int(task_dim), 32),
                nn.ReLU(),
                nn.Linear(32, int(width)),
            )
            if self.use_null_selector:
                self.selector_null = nn.Sequential(
                    nn.Linear(int(task_dim), 16),
                    nn.ReLU(),
                    nn.Linear(16, 1),
                )
        if self.use_polar_control:
            self.polar_control = PolarControlHead(task_dim=task_dim)
        self.task_dim = int(task_dim)
        self.width = int(width)
        self.max_action = float(max_action)
        center = (
            torch.zeros(self.task_dim, dtype=torch.float32)
            if task_center is None
            else torch.as_tensor(task_center, dtype=torch.float32).reshape(self.task_dim)
        )
        self.register_buffer("task_center", center)
        self.register_buffer("task_scale", torch.tensor(float(task_scale), dtype=torch.float32))

    def enable_polar_control(self) -> None:
        """Upgrade a loaded v1-v4 actor while retaining projector/selector weights."""
        if not self.use_task_selector:
            raise ValueError("polar control requires the task selector")
        if not self.use_polar_control:
            self.polar_control = PolarControlHead(task_dim=self.task_dim)
            self.use_polar_control = True

    def condition_task(self, task: torch.Tensor) -> torch.Tensor:
        """Expose small Qwen embedding differences to the hypernetworks."""
        return (task - self.task_center) * self.task_scale

    def entity_matrix(self, raw: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
        semantic = self.projector(raw[..., KIN_DIM:])
        entities = torch.cat((raw[..., :KIN_DIM], semantic), dim=-1)
        return entities * mask.unsqueeze(-1).to(entities.dtype)

    def target_logits(self, raw: torch.Tensor, task: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
        """Task-conditioned score for every entity; semantics themselves stay task-independent."""
        if not self.use_task_selector:
            raise RuntimeError("target selector is unavailable in a v1 checkpoint")
        no_batch = raw.dim() == 2
        if no_batch:
            raw = raw.unsqueeze(0)
        if task.dim() == 1:
            task = task.unsqueeze(0)
        if mask.dim() == 1:
            mask = mask.unsqueeze(0)
        mask = mask.bool()
        entities = self.entity_matrix(raw, mask)
        canonical = self.canonize(entities, mask)
        key = self.w_select(canonical)
        conditioned_task = self.condition_task(task)
        query = self.selector_hypernet(conditioned_task)
        logits = (key * query.unsqueeze(-2)).sum(dim=-1) / math.sqrt(float(self.width))
        logits = logits.masked_fill(~mask, -1.0e9)
        if self.use_null_selector:
            logits = torch.cat((logits, self.selector_null(conditioned_task)), dim=-1)
        return logits.squeeze(0) if no_batch else logits

    def forward(
        self,
        raw: torch.Tensor,
        task: torch.Tensor,
        mask: torch.Tensor,
        selector_override: torch.Tensor | None = None,
    ) -> torch.Tensor:
        no_batch = raw.dim() == 2
        if no_batch:
            raw = raw.unsqueeze(0)
        if task.dim() == 1:
            task = task.unsqueeze(0)
        if mask.dim() == 1:
            mask = mask.unsqueeze(0)
        if selector_override is not None and selector_override.dim() == 1:
            selector_override = selector_override.unsqueeze(0)
        mask = mask.bool()
        conditioned_task = self.condition_task(task)
        entities = self.entity_matrix(raw, mask)
        canonical = self.canonize(entities, mask)
        if not self.use_polar_control:
            # Only legacy control uses attention weights. Keep its parameters
            # for checkpoint compatibility, but skip this work for polar control.
            q = self.w_q(canonical)
            k = self.w_k(canonical)
            value_gain, output_gain = self.hypernet(conditioned_task)
            value = self.w_v(canonical) * value_gain.unsqueeze(-2)
            scores = q @ k.transpose(-2, -1) / math.sqrt(float(self.width))
            scores = scores.masked_fill(~mask.unsqueeze(-2), -1.0e9)
            scores = scores.masked_fill(~mask.unsqueeze(-1), -1.0e9)
            attention = torch.nan_to_num(torch.softmax(scores, dim=-1), nan=0.0)
            context = attention @ value
            output_weight = self.w_o.weight * output_gain.unsqueeze(-2)
            weights = (context * output_weight).sum(dim=-1) * mask.to(raw.dtype)
        if self.use_task_selector:
            if selector_override is None:
                selector_key = self.w_select(canonical)
                selector_query = self.selector_hypernet(conditioned_task)
                selector_logits = (selector_key * selector_query.unsqueeze(-2)).sum(dim=-1) / math.sqrt(
                    float(self.width)
                )
                selector_logits = selector_logits.masked_fill(~mask, -1.0e9)
                if self.use_null_selector:
                    selector_logits = torch.cat(
                        (selector_logits, self.selector_null(conditioned_task)), dim=-1
                    )
                selector = torch.nan_to_num(torch.softmax(selector_logits, dim=-1), nan=0.0)[..., :E_MAX]
            else:
                selector = selector_override.to(raw.dtype) * mask.to(raw.dtype)
                selector = selector / selector.sum(dim=-1, keepdim=True).clamp_min(1.0e-8)
        if self.use_task_selector and not self.use_polar_control:
            weights = weights * selector * mask.sum(dim=-1, keepdim=True).to(raw.dtype)
        if self.use_polar_control:
            selector_mass = selector.sum(dim=-1, keepdim=True)
            selected = (selector.unsqueeze(-1) * entities[..., :4]).sum(dim=-2)
            selected = selected / selector_mass.clamp_min(1.0e-8)
            action = self.max_action * self.polar_control(selected, conditioned_task)
            action = torch.where(selector_mass > 1.0e-8, action, torch.zeros_like(action))
        else:
            action = (weights.unsqueeze(-2) @ entities[..., :2]).squeeze(-2)
        action = torch.where(mask.any(dim=-1, keepdim=True), action, torch.zeros_like(action))
        norm = torch.linalg.norm(action, dim=-1, keepdim=True)
        if self.use_polar_control:
            action = action * torch.clamp(self.max_action / (norm + 1e-8), max=1.0)
        else:
            action = self.max_action * torch.tanh(norm) * action / (norm + 1e-8)
        return action.squeeze(0) if no_batch else action


def load_semantic_actor(path, map_location=None) -> SemanticAttentionActor:
    blob = torch.load(path, map_location=map_location, weights_only=False)
    architecture = blob.get("architecture")
    if architecture not in (
        "semantic16_attention_v1",
        "semantic16_attention_v2",
        "semantic16_attention_v3",
        "semantic16_attention_v4",
        "semantic16_attention_v5",
    ):
        raise ValueError("not a semantic16 actor checkpoint")
    model = SemanticAttentionActor(
        task_dim=int(blob["task_dim"]),
        width=int(blob["width"]),
        max_action=float(blob["max_action"]),
        use_task_selector=architecture in (
            "semantic16_attention_v2",
            "semantic16_attention_v3",
            "semantic16_attention_v4",
            "semantic16_attention_v5",
        ),
        use_null_selector=architecture in (
            "semantic16_attention_v3",
            "semantic16_attention_v4",
            "semantic16_attention_v5",
        ),
        use_polar_control=architecture == "semantic16_attention_v5",
        task_center=blob.get("task_center"),
        task_scale=float(blob.get("task_scale", 1.0)),
    )
    incompatible = model.load_state_dict(blob["state_dict"], strict=False)
    unexpected = list(incompatible.unexpected_keys)
    missing = [
        key
        for key in incompatible.missing_keys
        if key not in ("task_center", "task_scale")
    ]
    if missing or unexpected:
        raise RuntimeError(f"checkpoint mismatch missing={missing} unexpected={unexpected}")
    return model


class SemanticTorchActor:
    """Runtime wrapper accepting task-independent raw tracker observations."""

    expects_raw_entities = True

    def __init__(self, path, task_embed, device: str = "cpu") -> None:
        self.device = torch.device(device)
        self.net = load_semantic_actor(path, map_location=self.device).to(self.device).eval()
        self.task_embed = np.asarray(task_embed, dtype=np.float64).reshape(-1)
        if self.task_embed.size != self.net.task_dim:
            raise ValueError(f"task embedding {self.task_embed.size} != {self.net.task_dim}")
        self.max_action = self.net.max_action
        self._task = torch.as_tensor(self.task_embed, dtype=torch.float32, device=self.device)
        self.last_entities = np.zeros((0, ENTITY_DIM), dtype=np.float64)
        self.last_raw_entities = np.zeros((0, RAW_DIM), dtype=np.float64)
        self.last_target_probabilities = np.zeros((0,), dtype=np.float64)
        self.last_model_target_probabilities = np.zeros((0,), dtype=np.float64)
        self.last_null_probability = 0.0
        self.last_locked_target_index = None
        self.last_lock_similarity = -1.0
        self.last_target_misses = None
        self.last_track_ids = np.zeros((0,), dtype=np.int64)
        self.last_track_misses = np.zeros((0,), dtype=np.int64)
        self.last_track_hits = np.zeros((0,), dtype=np.int64)
        self.last_lock_confirmations = 0
        self._locked_appearance = None
        self._locked_track_id = None
        self._track_ids = None
        self._track_misses = None
        self._track_hits = None
        self._lock_candidate_id = None
        self._lock_candidate_hit = None
        self._lock_candidate_confirmations = 0

    def set_track_metadata(self, track_ids, track_misses, track_hits=None) -> None:
        """Attach tracker identity/freshness without adding them to model input."""
        self._track_ids = np.asarray(track_ids, dtype=np.int64).reshape(-1)
        self._track_misses = np.asarray(track_misses, dtype=np.int64).reshape(-1)
        self._track_hits = (
            None
            if track_hits is None
            else np.asarray(track_hits, dtype=np.int64).reshape(-1)
        )

    def _clear_lock_candidate(self) -> None:
        self._lock_candidate_id = None
        self._lock_candidate_hit = None
        self._lock_candidate_confirmations = 0

    def _confirm_lock_candidate(self, track_id: int, hit: int) -> int:
        """Count distinct detector updates, never repeated 10 Hz prediction ticks."""
        track_id, hit = int(track_id), int(hit)
        if self._lock_candidate_id != track_id:
            self._lock_candidate_id = track_id
            self._lock_candidate_hit = hit
            self._lock_candidate_confirmations = 1
        elif self._lock_candidate_hit != hit:
            self._lock_candidate_hit = hit
            self._lock_candidate_confirmations += 1
        return int(self._lock_candidate_confirmations)

    def __call__(self, raw_entities, task_embedding=None) -> tuple[float, float]:
        padded, mask = pack_raw_entities(raw_entities)
        raw = torch.as_tensor(padded, dtype=torch.float32, device=self.device)
        valid = torch.as_tensor(mask, dtype=torch.bool, device=self.device)
        task = self._task if task_embedding is None else torch.as_tensor(task_embedding, dtype=torch.float32, device=self.device)
        with torch.no_grad():
            entities = self.net.entity_matrix(raw, valid)
            if self.net.use_task_selector:
                target_probabilities = torch.softmax(
                    self.net.target_logits(raw, task, valid), dim=-1
                )
            else:
                target_probabilities = torch.zeros((0,), dtype=raw.dtype, device=raw.device)
            probabilities = target_probabilities.detach().cpu().numpy().astype(np.float64)
            n_valid = int(mask.sum())
            null_probability = (
                float(probabilities[-1])
                if self.net.use_null_selector and probabilities.size
                else 0.0
            )
            forced_index = None
            lock_similarity = -1.0
            current_raw = padded[:n_valid]
            track_ids = self._track_ids
            track_misses = self._track_misses
            track_hits = self._track_hits
            metadata_valid = (
                track_ids is not None
                and track_misses is not None
                and len(track_ids) == n_valid
                and len(track_misses) == n_valid
            )
            hit_metadata_valid = (
                metadata_valid
                and track_hits is not None
                and len(track_hits) == n_valid
            )
            if self._locked_track_id is not None and metadata_valid:
                matches = np.flatnonzero(track_ids == int(self._locked_track_id))
                if matches.size:
                    forced_index = int(matches[0])
                    _, lock_similarity = appearance_match_index(
                        current_raw[forced_index : forced_index + 1], self._locked_appearance
                    )
                else:
                    # The tracker has retired that identity.  Do not silently
                    # transfer the lock to a visually similar distractor.
                    self._locked_track_id = None
                    self._locked_appearance = None
                    self._clear_lock_candidate()
            if forced_index is not None and hit_metadata_valid and probabilities.size:
                best = int(np.argmax(probabilities[:n_valid]))
                current_probability = float(probabilities[forced_index])
                challenger_probability = float(probabilities[best])
                challenger_is_fresh = int(track_misses[best]) == 0
                if (
                    best != forced_index
                    and challenger_is_fresh
                    and challenger_probability >= 0.85
                    and current_probability <= 0.15
                ):
                    confirmations = self._confirm_lock_candidate(
                        int(track_ids[best]), int(track_hits[best])
                    )
                    if confirmations >= 3:
                        self._locked_track_id = int(track_ids[best])
                        self._locked_appearance = current_raw[best, KIN_DIM:].copy()
                        forced_index = best
                        lock_similarity = 1.0
                        self._clear_lock_candidate()
                else:
                    self._clear_lock_candidate()
            if self._locked_appearance is None and n_valid and probabilities.size:
                best = int(np.argmax(probabilities[:n_valid]))
                fresh = not metadata_valid or int(track_misses[best]) == 0
                if (
                    fresh
                    and float(probabilities[best]) >= 0.70
                    and float(probabilities[best]) > null_probability
                ):
                    self._locked_appearance = current_raw[best, KIN_DIM:].copy()
                    if metadata_valid:
                        self._locked_track_id = int(track_ids[best])
                    forced_index = best
                    lock_similarity = 1.0
                    self._clear_lock_candidate()
                else:
                    self._clear_lock_candidate()
            elif self._locked_appearance is not None and forced_index is None:
                forced_index, lock_similarity = appearance_match_index(
                    current_raw, self._locked_appearance
                )
                if forced_index is not None:
                    observed = current_raw[forced_index, KIN_DIM:]
                    updated = 0.9 * self._locked_appearance + 0.1 * observed
                    norm = float(np.linalg.norm(updated))
                    self._locked_appearance = updated / norm if norm > 1e-9 else updated
            selector_override = None
            if forced_index is not None:
                selector_override = torch.zeros(E_MAX, dtype=raw.dtype, device=self.device)
                selector_override[forced_index] = 1.0
            action = self.net(raw, task, valid, selector_override=selector_override)
        self.last_entities = entities[valid].detach().cpu().numpy().astype(np.float64)
        self.last_raw_entities = raw[valid].detach().cpu().numpy().astype(np.float64)
        self.last_track_ids = (
            np.asarray(track_ids, dtype=np.int64).copy()
            if metadata_valid
            else np.arange(n_valid, dtype=np.int64)
        )
        self.last_track_misses = (
            np.asarray(track_misses, dtype=np.int64).copy()
            if metadata_valid
            else np.zeros(n_valid, dtype=np.int64)
        )
        self.last_track_hits = (
            np.asarray(track_hits, dtype=np.int64).copy()
            if hit_metadata_valid
            else np.zeros(n_valid, dtype=np.int64)
        )
        self.last_lock_confirmations = int(self._lock_candidate_confirmations)
        self.last_locked_target_index = forced_index
        self.last_lock_similarity = float(lock_similarity)
        self.last_target_misses = (
            int(track_misses[forced_index])
            if forced_index is not None and metadata_valid
            else None
        )
        if self.net.use_null_selector and probabilities.size:
            self.last_model_target_probabilities = probabilities[:-1].copy()
            if forced_index is not None:
                effective = np.zeros_like(probabilities[:-1])
                effective[forced_index] = 1.0
                self.last_target_probabilities = effective
                self.last_null_probability = 0.0
            else:
                self.last_target_probabilities = probabilities[:-1]
                self.last_null_probability = float(probabilities[-1])
        else:
            self.last_target_probabilities = probabilities
            self.last_model_target_probabilities = probabilities.copy()
            self.last_null_probability = 0.0
        return float(action[0]), float(action[1])
